{
<<<<<<< HEAD
	"wellSkyCPRPlusDbHost": "DbHost",
	"enableEncryption":0,
	"encryptedWellskydDbCredentials":"hashedkeyhere",
	"wellSkyCPRPlusDbName": "DbName",
	"wellSkyCPRPlusDbUser": "DbUser",
	"wellSkyCPRPlusDbPassoword": "DbPassoword",
	"wellSkyCPRPlusDbPort":1433,
	"CPRPlusDbinstanceName":"DbinstanceName",
	"wellSkyCPRPlusDbTimeZoneOffset":-4,
	"wellSkyCPRPlusDbPollingInterval":-1,
	"filingCenterPath": "/src/progress_notes/json/",
	"directLinkingPath":"/src/directLinking/",
	"faxQueuePath":"/src/",
	"faxqueuePathPattern":"[serverpath]/[YYYYMM]/[[MRN]/[FileName]",
	"accountName": "Tenant account name",
	"accountId": "Tenant account id",
	"ModuleId": "Tenant Module id",
	"enviornment": "Enviornment",
	"isMultiBranch":0,
	"enableStoredProcedureForProgressNote":0,
	"progressNoteStoredProcedureName":"CH_SP_Insert_Progress_Note",
	"documentReferenceStoredProcedureName":"CH_SP_Insert_Document",
    "enableStoredProcedureForDocumentReference":0,
	"integrationType":"site/company",
	"integrationMode":"create/update",
	"isGroupSiteOnboarding":0,
    "multiSites":"",
    "rxAlerts" : 0,
    "enableDLtiffconversion" : 1
	
}
=======
     "wellSkyCPRPlusDbHost": "",
     "enableEncryption": 0,
     "encryptedWellskydDbCredentials": "9435fcb2c647d494f8248615d3655fd68c8ca1c063e63c1307e08eee36efe4c7",
     "wellSkyCPRPlusDbName": "",
     "wellSkyCPRPlusDbUser": "",
     "wellSkyCPRPlusDbPassoword": "",
     "wellSkyCPRPlusDbPort": 1433,
     "wellSkyCPRPlusDbTimeZoneOffset": -4,
     "wellSkyCPRPlusDbPollingInterval": -2,
     "filingCenterPath": "/src/progress_notes/json/",
     "directLinkingPath": "/src/directLinking/",
     "faxqueuePathPattern": "[serverpath]/[YYYYMM]/[FileName]",
     "accountName": "NELC",
     "accountId": "NELC",
     "ModuleId": "NELC Fhir facade",
     "enviornment": "Production",
     "isMultiBranch": 0,
     "enableStoredProcedureForProgressNote": 0,
     "enableStoredProcedureForDocumentReference": 0,
     "progressNoteStoredProcedureName": "CH_SP_Insert_Progress_Note",
     "documentReferenceStoredProcedureName": "CH_SP_Insert_Document",
     "integrationType": "site",
     "integrationMode": "update",
     "isGroupSiteOnboarding": 0,
     "multiSites": "",
     "rxAlerts": 0,
     "patientSearchQuery":""
}
>>>>>>> 865f0604841c3cb4a1d032cc024a2cbec430735e
