{
		"wellSkyCPRPlusFHIRFacadeURL": "http://192.168.1.172:3000/3_0_1",
		"wellSkyCPRPlusFHIRFacadeUserName": "xxxxxxxx",
		"wellSkyCPRPlusFHIRFacadePassword": "xxxxxxxx",
		"wellSkyPatientPollingFrequencyInMinutes": "1",
		"wellSkyPatientRecordDurationInMinutes": "1",
		"citusFacadeUrl": "https://fhir.optionone.sandbox.citushealth.com/3_0_1",
		"citusFHIRFacadeUserName": "xxxxxxxx",
		"citusFHIRFacadePassword":"xxxxxxxx",
		"accountId" : "tenant accountId",
		"accountName" : "tenant accountName",
		"env" : "DB env",
		"CitusCompositionPollingFrequencyInMinutes": "1",
		"CitusCompositionRecordDurationInMinutes": "1",
		"wellSkyCPRPlusToCitusLastUpdatedTimeFile":"/data/last_update.json",
		"logFilePath":"/data/logs/",
		"CitusToWellSkyCPRPlusLastUpdatedTimeFile":"",
		"CitusToWellSkyCPRPlusLogFileLocation":"",
		"citusProgressNoteFolderPollingFrequencyInMinutes": "1",
		"citusProgressNoteFolderPath":"/opt/progressNotes/",
		"archiveFolderPath":"/opt/Archives/",
		"wellSkyPatientPollingWithUpsert":false,
		"failedFolderPath":"/opt/failedFiles/",
		"pollingOffset" : 0,
		"successStatusCode":201

}