---
- name: Citus Health Integration Engine (CHIE) CCF Containers
  hosts: all
  vars_files:
    - ../conf/appliance.secrets.conf.yml
    - ../conf/appliance.common.conf.yml
  tasks:
    - name: Clone Citus Health Integration Engine (CHIE) CCF Containers
      git:
       name: https://{{ chp_github_account | urlencode }}:{{ chp_github_account_token | urlencode }}@github.com/CitusHealthIntegrationEngine/{{ chp_github_accout_name }}.git
       dest: '{{citus_health_containers_path}}'
       force: yes
       
    - name: Create Appliance Admin User Common runtime config and Secrets directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - '{{ appliance_admin_user_common_runtime_config_directory }}'
        - '{{ appliance_admin_user_secrets_directory }}' 

    - name: Go to Traefik directory and install Traefik routing CCF Container service
      command: chdir={{ traefik_ccf_container_path }} ccfmake start

    - name: Go to Wellsky CPR PLUS FHIR Facade directory and install Wellsky CPR PLUS FHIR Facade CCF container service
      command: chdir={{ wellsky_cpr_fhir_facade_path }} ccfmake start

    - name: Go to FHIR Sync directory and install FHIR Sync CCF container service
      command: chdir={{ fhir_sync_ccf_container_path }} ccfmake start

    - name: Go to Nextgen Mirth Connect directory and install Nextgen Mirth Connect CCF container service
      command: chdir={{ nextgen_mirth_connect_path }} ccfmake configure
    
    - name: Go to Prometheus directory and install Prometheus CCF container service
      command: chdir={{ prometheus_ccf_container_path }} ccfmake start

    - name: Go to Portainer directory and install Portainer to manage the dockers installaed in the system
      command: chdir={{ portainer_ccf_container_path }} ccfmake start
    
    - name: Go to Grafana directory and install Grafana CCF container service
      command: chdir={{ grafana_ccf_container_path }} ccfmake start

